runtime: php
env: flex

runtime_config:
  operating_system: "ubuntu18"
  runtime_version: "7.4"
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
    - .env

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100

#handlers:
    #- url: /css
      #static_dir: public/css

env_variables:
    # Put production environment variables here.
    APP_DEBUG: true
    APP_ENV: production
    APP_KEY: base64:jV6q8nvEbAtS/Na1juYW/8Cy0MpOVEGUi4ShYyDaOic=
    APP_NAME: "GCP App - CODE"

    LOG_LEVEL: debug

    DB_CONNECTION: mysql
    DB_HOST: 127.0.0.1
    DB_DATABASE: db_1
    DB_USERNAME: root
    DB_PASSWORD: Tito456@
    DB_SOCKET: '/cloudsql/plated-sunup-394607:us-central1:gcp-app-db-instance-1'

beta_settings:
    cloud_sql_instances: 'plated-sunup-394607:us-central1:gcp-app-db-instance-1'
